Updated README
BIBSYSDEV/nva-customer-api pull request #23
Opened 2020-09-16 13:13 UTC by janbj

2020-09-16 15:02 UTC, brinxmat requested changes

2020-09-16 15:02 UTC, brinxmat commented on README.md
> +## Deploy considerations
Deployment

2020-09-16 15:02 UTC, brinxmat commented on README.md
> +These resources are defined outside the SAM template but used in the template.
, but

2020-09-17 08:55 UTC, norrs requested changes
The environment variables defined in Environment should be documented as they act as configuration for the application. Application configuration is nice to document.

2020-09-17 08:55 UTC, norrs commented on README.md
> +These resources are defined outside the SAM template but used in the template.
A link to nva-deploy doesn't hurt.

2020-09-18 14:12 UTC, brinxmat approved these changes

2020-09-21 06:51 UTC, norrs commented on README.md
> +date before deploying new SAM template.
This is good enough for now, but ideally we want these dynamodb changes to be defined in `template.yaml` as for the rest of the service when we know how to handle our migrations on persistent databases with cloudformation.

2020-09-21 06:51 UTC, norrs approved these changes

2020-09-22 07:01 UTC, merged